PRINT "TYPE CF TO CONVERT FROM CELCIUS TO FAHRENHEIT AND FC TO CONVERT FROM FAHRENHEIT TO CELCIUS"
INPUT C$
IF C$ = "CF" THEN
  PRINT "INPUT CELCIUS"
  INPUT B
  ANS=B*9/5+32
  PRINT  ANS
ELSEIF C$ = "FC" THEN
  PRINT "INPUT FAHRENHEIT"
  INPUT B
  ANSS=B-32*5/9
  PRINT ANSS
ELSE 
 PRINT "YOU ENTERED WRONG LETTER ENTER CF OR FC"
END IF
END

